SEEDS = {
    'tomatoes': ['Помидоры', [['Йетина Мать', 'https://www.wildberries.ru/catalog/181951026/detail.aspx?targetUrl=EX'],
                              ['Кулема', 'https://www.wildberries.ru/catalog/142646175/detail.aspx'],
                              ['Сердцеедка', 'https://www.wildberries.ru/catalog/54666901/detail.aspx?targetUrl=EX']]],
    'cucumbers': ["Огурцы", [['Лихач', 'https://www.wildberries.ru/catalog/19110693/detail.aspx?targetUrl=SG'],
                             ['Директор', 'https://www.wildberries.ru/catalog/19110707/detail.aspx?targetUrl=EX'],
                             ['Бинго', 'https://www.wildberries.ru/catalog/19110931/detail.aspx?targetUrl=EX']]],
    'peppers': ["Болгарские перцы", [['Катюша', 'https://www.wildberries.ru/catalog/23782377/detail.aspx'],
                                     ['Витамин',
                                      'https://www.wildberries.ru/catalog/23782365/detail.aspx?targetUrl=EX'],
                                     ['Добрыня Никитич',
                                      'https://www.wildberries.ru/catalog/23782372/detail.aspx?targetUrl=EX']]],
    'zucchini': ["Кабачки", [['Хьюго', 'https://www.wildberries.ru/catalog/19110928/detail.aspx'],
                             ['Искандер', 'https://www.wildberries.ru/catalog/19110772/detail.aspx?targetUrl=EX'],
                             ['Зебра', 'https://www.wildberries.ru/catalog/19110997/detail.aspx?targetUrl=EX']]],
    'carrot': ["Морковь", [['Краса Севера', 'https://www.wildberries.ru/catalog/22185923/detail.aspx?targetUrl=SG'],
                           ['Дарина', 'https://www.wildberries.ru/catalog/22185921/detail.aspx?targetUrl=SG'],
                           ['Санькина любовь',
                            'https://www.wildberries.ru/catalog/190169618/detail.aspx?targetUrl=SG']]],
    'strawberry': ["Клубника", [['Гигантелла', 'https://www.wildberries.ru/catalog/40413647/detail.aspx?targetUrl=EX'],
                                ['Красная пчелка',
                                 'https://www.wildberries.ru/catalog/149270382/detail.aspx?targetUrl=EX'],
                                ['Королева Елизавета',
                                 'https://www.wildberries.ru/catalog/40413652/detail.aspx?targetUrl=EX']]]
}